### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by aviau** [influxdb/influxdb-python#109]
**TODO LIST**

- [ ] Review the docs
- [ ] Update and test all the tutorials
- [ ] Fix the DataFrameClient and improve coverage (see #108 )
- [ ] Implement more operations (user management, etc.)

**DONE**
- [x] Debug UDP support (I couldn't get it working)
- [x] Fix the SeriesHelper
- [x] Support writing in batch (see #102)

**Comment by dashesy** [comment]
I have a small working library that plan to make it into Pandas, you can take a look if you want [here](https://github.com/dashesy/pandas-tsdb/tree/master/influxdb)

**Comment by ReAzem** [comment]
@dashesy Would you keep me updated on that please? If this is ever merged in pandas I would love to support it in the lib.

**Comment by areski** [comment]
The test coverage on DataFrameClient is quite weak, it might be nice to add this to the TODO.

**Comment by ReAzem** [comment]
Noted.

**Comment by cannium** [comment]
As I noticed, v0.9 supports clustering. Does influxdb-python supports connecting to multiple hosts(a cluster) now? I think the new version should handle cluster properly.

**Comment by gst** [comment]
about :
>  Debug UDP support (I couldn't get it working)

it's (very "simply", with write_points() method) tested in last version.. within class UdpTests.. which could probably be extended with others udp tests more advanced, eventually.

**Comment by cannium** [comment]
I posted a [pull request](https://github.com/influxdb/influxdb-python/pull/148) for clustering. Please review.

**Comment by gst** [comment]
@ReAzem 
I was still asking myself why you tagged "so quickly" and more important : why you taggeg with v1.0.0.. (and the 1.0.1 & 1.0.2)..

we could have had/followed the same (at least major) version than the server.. now it's over unless we delete the tags.. (which I'd vote for but it depends..)

wdyt ?

**Comment by ReAzem** [comment]
@gst 

The versioning of the lib has nothing to do with the versioning of the server. This is not the same project.

I am following the [semver](http://semver.org/) spec.

major.minor.fix

Everytime the API breaks: major release
Every new feature: minor release
Every bug fix: fix release

**Comment by gst** [comment]
> The versioning of the lib has nothing to do with the versioning of the server. This is not the same project.

that is a shame ! ;) no kidding ;) Ofcourse there aren't the same project :p but they are quite tightly coupled.. aren't they ?  
I find that it's quite often that a client follow the same version (at least major) than the server for which it is the client .. just for the sake of clarity / simplicity.. 
examples : mysql , postgres , others..  

then why did you raised from v0.4.1 to v1.0.0 .. ?   we certainly could have had v0.9-rcXX :s

> The next tag will be 2.0.0 because we broke the API with ResultSet.

because you already tagged v1.0.0 previously ;) which I still don't see a/the reason actually..

**Comment by ReAzem** [comment]
> I find that it's quite often that a client follow the same version (at least major) than the server for which it is the client

Can't do that and respect semver at the same time. I think semver is more important than this.

> then why did you raised from v0.4.1 to v1.0.0 .. ? we certainly could have had v0.9-rcXX :s

I wanted to release to Pypi ASAP because of the influxdb08 sub-module. This was a good time so I released 1.0.0. 1.0.0 should have been released a long time ago,but I didn't manage versioning at this time.

See the Semver Specification:

>How do I know when to release 1.0.0?
>
If your software is being used in production, it should probably already be 1.0.0. If you have a stable API on which users have come to depend, you should be 1.0.0. If you're worrying a lot about backwards compatibility, you should probably already be 1.0.0.

**Comment by gst** [comment]
ok for the Semver spec..

but hell : 

> How do I know when to release 1.0.0?
> If your software is being used in production, it should probably already be 1.0.0.

:| there are people using influxdb-server (but v0.8 then...) and its python-client in production (which should then be influxdb-python v0.4.1 ....) ??

**Comment by ReAzem** [comment]
> :| there are people using influxdb-server (but v0.8 then...) and its python-client in production (which should then be influxdb-python v0.4.1 ....) ?? 

Yes:
> influxdb/influxdb-python/pull/99
> ChristopherRabotin:
> I hope to start using influxdb in prod starting the middle of next week. :D

I will absolutely keep respecting the semver spec. I will also **never** revert a tag. PyPI won't let me do it and its just terrible practice anyways.

**Comment by ChristopherRabotin** [comment]
I confirm, if need be, that I use influxdb python in production.

**Comment by gst** [comment]
points taken.

> PyPI won't let me do it and its just terrible practice anyways

yeah I know..  PyPI is just right in that.

**Comment by peterchou91** [comment]
1 from influxdb.influxdb08 import InfluxDBClient
  2 
  3 json_body = [{"name": "cpu_load_short","timestamp": "2009-11-10T23:00:00Z","name":"1"}]
  4 client = InfluxDBClient('10.136.108.128', 8086, 'root', 'root', 'example')
  5 client.create_database('example')
  6 client.write_points(json_body)
  7 result = client.query('select * from cpu_load_short;')
  8 print("Result: {0}".format(result))
  when the program above finish,it prints:
Traceback (most recent call last):
  File "test.py", line 8, in <module>
    result = client.query('select * from cpu_load_short;')
  File "/usr/lib/python2.7/site-packages/influxdb/influxdb08/client.py", line 419, in query
    chunked=chunked)
  File "/usr/lib/python2.7/site-packages/influxdb/influxdb08/client.py", line 447, in _query
    expected_response_code=200
  File "/usr/lib/python2.7/site-packages/influxdb/influxdb08/client.py", line 255, in request
    raise InfluxDBClientError(response.content, response.status_code)
influxdb.influxdb08.client.InfluxDBClientError: 400: Couldn't find series: cpu_load_short

this is so wired,i can't figure it out,can anybody help me ?
thanks

**Comment by ChristopherRabotin** [comment]
@peterchou91 you're attempting to read from a time series which does not exist. If you think it exists, can you check that it is indeed called `cpu_load_short`? To create that time series, all you need to do is write points to it.

**Comment by richard-kti** [comment]
Any reason not to be using this module with 0.9.x now ?

**Comment by aviau** [comment]
@richard-kti The module support 9.0.x.

**Comment by brewneaux** [comment]
Should this be updated to use line instead of JSON?

**Comment by aviau** [comment]
> Should this be updated to use line instead of JSON?

Already done.

**Comment by brewneaux** [comment]
I must have missed that, my apologies.

**Comment by aviau** [comment]
I was using this issue when doing the transition to 0.9.0 and taking over the repository. I don't think it is useful anymore, as it is turning into a forum. I'll close this.
